services:
  postgres:
    image: postgres:15
    container_name: maria-chef-postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: maria_chef
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:15
    container_name: maria-chef-postgres-test
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: maria_chef_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    command: >
      postgres  -c fsync=off  -c synchronous_commit=off  -c full_page_writes=off

volumes:
  postgres_data:
  postgres_test_data:
